version: "3.9"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: lmsdb
        MYSQL_USER: lmsuser
        MYSQL_PASSWORD: lmsuserpwd

  lms-adminer:
    image: adminer:latest
    container_name: lms-adminer
    ports:
       - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    depends_on:
        - mysqldb